import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync,writeFileSync,mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createApp } from '../src/server.mjs';
import { newKey,exportKey,pack,request,walletId } from '../src/protocol.mjs';
async function fixture(t,options={}){const dir=mkdtempSync(join(tmpdir(),'paila-http-'));const app=createApp({dir,rateLimit:false,...options});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+app.server.address().port;t.after(async()=>{await new Promise(r=>app.server.close(r));app.ledger.close();rmSync(dir,{recursive:true,force:true});});return {...app,url};}
const post=(url,envelope,extra={})=>fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...extra},body:JSON.stringify({envelope})});
test('health check does not leak keys or wallet data',async t=>{const f=await fixture(t);const r=await fetch(f.url+'/health');assert.equal(r.status,200);assert.deepEqual(await r.json(),{status:'ok',mode:'test',version:'0.1.0'});assert.equal(r.headers.get('x-content-type-options'),'nosniff');});
test('empty, malformed, oversized and wrong content types are handled',async t=>{const f=await fixture(t);for(const [body,type,status]of [['{','application/json',400],['{}','application/json',400],['{}','text/plain',415],['a'.repeat(40000),'application/json',413]]){const r=await fetch(f.url+'/v1/actions',{method:'POST',headers:{'Content-Type':type},body});assert.equal(r.status,status);assert((await r.json()).error.code);}});
test('cross-origin browser calls and sensitive filesystem routes are rejected',async t=>{const f=await fixture(t);let r=await post(f.url+'/v1/wallets','invalid',{Origin:'https://evil.example'});assert.equal(r.status,403);for(const p of ['/data/issuer-private.pem','/src/server.mjs','/v1/accounts','/lab'])assert.equal((await fetch(f.url+p)).status,404);});
test('API registration and parallel replay are exactly once',async t=>{const f=await fixture(t);const k=newKey(),pub=exportKey(k.publicKey),id=walletId(pub);const registration=pack('register',{v:1,publicKey:pub,name:'HTTP tester',ts:Date.now(),opId:randomUUID()},k.privateKey);const regs=await Promise.all(Array.from({length:8},()=>post(f.url+'/v1/wallets',registration)));for(const r of regs)assert.equal((await r.json()).balanceMinor,100000);const raw=request(k.privateKey,id,'reserve',{amountMinor:10000});const replies=await Promise.all(Array.from({length:25},()=>post(f.url+'/v1/actions',raw).then(r=>r.json())));assert(replies.every(r=>r.id===replies[0].id));assert.equal(f.ledger.state(id).balanceMinor,90000);assert(f.ledger.audit().ok);});
test('parallel competing online spends cannot overdraw',async t=>{const f=await fixture(t);const people=[];for(let i=0;i<3;i++){const k=newKey(),pub=exportKey(k.publicKey),id=walletId(pub);await post(f.url+'/v1/wallets',pack('register',{v:1,publicKey:pub,name:'User '+i,ts:Date.now(),opId:randomUUID()},k.privateKey));people.push({...k,id});}const [a,b,c]=people;const responses=await Promise.all([b,c].map(p=>post(f.url+'/v1/actions',request(a.privateKey,a.id,'pay',{to:p.id,amountMinor:80000}))));assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);assert.equal(f.ledger.state(a.id).balanceMinor,20000);assert(f.ledger.audit().ok);});
test('no fake APK download: returns 404 before an APK is built',async t=>{const f=await fixture(t);const r=await fetch(f.url+'/downloads/paila-test.apk');assert.equal(r.status,404);assert.match((await r.json()).error.message,/No APK/);});
test('rate limiting returns retry-after without trusting forwarded IP',async t=>{const f=await fixture(t,{rateLimit:true});let r;for(let i=0;i<181;i++)r=await fetch(f.url+'/health',{headers:{'X-Forwarded-For':'203.0.113.'+(i%250)}});assert.equal(r.status,429);assert.equal(r.headers.get('retry-after'),'60');});
