from pathlib import Path
from bs4 import BeautifulSoup
import json,base64,os
p=Path(__file__).resolve().parent.parent;q=Path(os.environ.get('QA_OUTPUT',str(p/'qa'/'qa-output')))
items=[('wallet','Wallet','02-wallet'),('send','Send','13-review'),('receive','Receive','18-receive-own'),('offline','Offline pocket','04-offline'),('activity','Activity','16-activity-settled'),('settings','Settings','08-settings'),('setup','Onboarding','01-setup'),('pending','Pending receipt','07-pending'),('saved','Saved payment','06-payment'),('error','Invalid code','09-error')]
scenes={}
for key,label,name in items:
 doc=BeautifulSoup((q/(name+'.html')).read_text(),'html.parser');app=doc.select_one('#app');assert app
 for img in app.select('img'):
  if 'data:image/webp' in img.get('src',''):img['src']='__PAILA_ART__'
  else:img['src']='__PAILA_LOGO__'
 scenes[key]={'label':label,'html':app.decode_contents()}
dialogs={}
for key,name in [('review','13-review'),('nearby','14-nearby')]:
 doc=BeautifulSoup((q/(name+'.html')).read_text(),'html.parser');dialogs[key]=doc.select_one('#confirm').decode_contents()
art='data:image/webp;base64,'+base64.b64encode((p/'web/wallet-art.webp').read_bytes()).decode();logo='data:image/svg+xml;base64,'+base64.b64encode((p/'web/logo.svg').read_bytes()).decode()
css=(p/'web/app.css').read_text()
extra='''
.preview-bar{max-width:1120px;margin:0 auto;padding:16px 24px;display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.preview-title{font-size:16px;font-weight:600;letter-spacing:-.3px}.preview-subtitle{font-size:14px;color:var(--muted);margin-top:2px}.preview-tools{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.preview-tools select{width:auto;min-width:120px;min-height:44px;padding:8px 28px 8px 12px;border-radius:99px;font-size:14px}.preview-tools button{min-height:44px;border:1px solid var(--control);padding:8px 16px;border-radius:99px;background:var(--card);font-size:14px}.preview-tools label{flex-direction:row;align-items:center;gap:8px;min-height:44px}.preview-tools input{min-height:20px;width:20px;height:20px;padding:0}.preview-note{font-size:14px;color:var(--muted)}#preview-toast{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);background:var(--primary);color:var(--on-primary);padding:14px 20px;border-radius:20px;max-width:calc(100% - 32px);font-size:14px;box-shadow:0 12px 30px #0002;z-index:99;pointer-events:none}#preview-toast:empty{display:none}.phone{height:calc(100dvh - 112px)}@media(min-width:1000px){.phone{margin:0 auto 16px}}@media(max-width:620px){.preview-bar{padding:12px 16px;gap:10px}.preview-tools{width:100%;gap:6px}.preview-tools select{flex:1;min-width:100px}.preview-tools button{padding:8px 12px}.preview-tools label{font-size:14px}.preview-title{font-size:16px}}
:root[data-reduced=true] *,:root[data-reduced=true] *:before,:root[data-reduced=true] *:after{animation:none!important;transition:none!important}
'''
script=r'''
const records=JSON.parse(document.getElementById('preview-data').textContent),app=document.getElementById('app'),dialog=document.getElementById('confirm'),choice=document.getElementById('screen-choice');let current='wallet',appearance='auto';
const reduced=()=>document.getElementById('reduce-motion').checked||matchMedia('(prefers-reduced-motion:reduce)').matches;
const expand=s=>s.replaceAll('__PAILA_ART__',records.art).replaceAll('__PAILA_LOGO__',records.logo);
function toast(text){const n=document.getElementById('preview-toast');n.textContent=text;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>n.textContent='',3200)}
function fit(){const extra=innerWidth>=1000?16:0;app.style.height=Math.max(500,innerHeight-document.querySelector('.preview-bar').offsetHeight-extra)+'px';const nav=app.querySelector('.navigation'),pill=app.querySelector('.nav-pill');if(nav&&pill){const i=[...nav.querySelectorAll('.nav-item')].findIndex(n=>n.classList.contains('active'));pill.style.transform=innerWidth>=1000?`translateY(${i*60}px)`:`translateX(${i*100}%)`}}
function show(key){if(!records.scenes[key])return;if(dialog.open)dialog.close();current=key;choice.value=key;app.innerHTML=expand(records.scenes[key].html);app.querySelectorAll('textarea[name=recipient]').forEach(n=>{n.readOnly=true;n.setAttribute('aria-description','Captured test code; this design preview does not verify payments')});app.querySelectorAll('[data-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.theme===appearance)));fit();if(!reduced())app.querySelector('.screen-content')?.animate([{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'translateY(0)'}],{duration:280,easing:'cubic-bezier(.2,.8,.2,1)'});}
function theme(value){appearance=value;document.documentElement.dataset.theme=value;document.getElementById('theme-choice').value=value;app.querySelectorAll('[data-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.theme===value)))}
function openDialog(kind){dialog.innerHTML=expand(records.dialogs[kind]);const form=dialog.querySelector('form');if(kind==='review'){const field=app.querySelector('#send-form [name=amount]');const value=Number(field?.value);if(Number.isFinite(value)&&value>0)dialog.querySelector('.review-amount').textContent='Rs '+value.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});const notice=document.createElement('p');notice.className='small muted';notice.textContent='Design preview only. This example sends no payment and does not validate codes.';form.insertBefore(notice,form.children[2]);}dialog.showModal();}
function info(title,text){dialog.innerHTML='<form method="dialog"><div class="sheet-handle" aria-hidden="true"></div><h2 id="dialog-title"></h2><p class="small muted"></p><button class="primary" value="cancel">Got it</button></form>';dialog.querySelector('h2').textContent=title;dialog.querySelector('p').textContent=text;dialog.showModal()}
choice.addEventListener('change',()=>show(choice.value));document.getElementById('theme-choice').addEventListener('change',e=>theme(e.target.value));document.getElementById('replay').addEventListener('click',()=>{show(current);if(reduced())toast('Motion is off for your reduced-motion setting.')});document.getElementById('reduce-motion').addEventListener('change',e=>{document.documentElement.dataset.reduced=e.target.checked?'true':'false';if(e.target.checked)document.getAnimations().forEach(a=>a.finish())});
app.addEventListener('click',async e=>{const anchor=e.target.closest('a');if(anchor){e.preventDefault();show('wallet');return}const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.nav){show(({Wallet:'wallet',Send:'send',Receive:'receive',Offline:'offline',Activity:'activity',Settings:'settings'})[b.dataset.nav]);return}if(b.dataset.theme){theme(b.dataset.theme);return}if(b.dataset.method){app.querySelectorAll('[data-method]').forEach(n=>{n.classList.toggle('selected',n===b);n.setAttribute('aria-pressed',String(n===b))});toast('Method style preview. Run the included server to exchange test money.');return}if(b.dataset.preset){const input=app.querySelector('#reserve-form [name=amount]');if(input)input.value=b.dataset.preset;return}if(b.dataset.outbox){show('saved');return}if(b.dataset.refund){info('Refund preview','No refund is made in this design preview. The working test client checks note expiry with its server.');return}switch(b.dataset.action){case'dismiss':b.closest('.notice')?.remove();break;case'radios':openDialog('nearby');break;case'topup':info('Test credit preview','The working app adds Rs 1,000 through its test server. This design viewer cannot create credit.');break;case'sync':toast('Design preview: there is no server connection here.');break;case'copy-receive':case'copy-payment':{const field=app.querySelector(b.dataset.action==='copy-receive'?'#receive-code':'#payment-code');try{await navigator.clipboard.writeText(field.value);toast('Copied a captured test code, not live payment credit.')}catch{field.closest('details')?.setAttribute('open','');field.focus();field.select();toast('Select and copy this captured test code.')}break;}}});
app.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='send-form'){if(current==='error'){toast('Invalid-code example. Ask the sender for a new code.');return}openDialog('review');return}if(e.target.id==='setup-form'){info('Onboarding preview','No account is created here. The source package contains the real browser test client and server.');return}info('Interface preview','No credit or receipt was created. Use the runnable app in the source package to test this operation.');});
dialog.addEventListener('submit',e=>{e.preventDefault();const confirmed=e.submitter?.value==='confirm';dialog.close();if(confirmed)toast('Preview complete. No payment was sent.');});
window.addEventListener('resize',fit);window.PailaPreview={show,openDialog,scenes:Object.keys(records.scenes)};show('wallet');
'''
options=''.join('<option value="'+key+'">'+v['label']+'</option>' for key,v in scenes.items())
record=json.dumps({'scenes':scenes,'dialogs':dialogs,'art':art,'logo':logo},ensure_ascii=False).replace('</','<\\/')
html='''<!doctype html><html lang="en" data-theme="auto"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>Paila · Interactive design preview</title><style>'''+css+extra+'''</style></head><body><header class="preview-bar"><div><p class="preview-title">Paila / Interface v2</p><p class="preview-subtitle">Captured test states. No payments or accounts are created here.</p></div><div class="preview-tools"><select id="screen-choice" aria-label="Preview screen">'''+options+'''</select><select id="theme-choice" aria-label="Preview theme"><option value="auto">System</option><option value="light">Light</option><option value="dark">Dark</option></select><button id="replay">Replay motion</button><label><input id="reduce-motion" type="checkbox">Reduce motion</label></div></header><div id="app" class="phone"></div><dialog id="confirm" aria-labelledby="dialog-title"></dialog><div id="preview-toast" role="status" aria-live="polite"></div><script id="preview-data" type="application/json">'''+record+'''</script><script>'''+script+'''</script></body></html>'''
out=(p/'Paila-interactive-design.html');out.write_text(html);(p/out.name).write_text(html)
print('Created',out.name,len(html.encode()),'bytes;',len(scenes),'interactive scene states. Explicitly not a live wallet.')
