/* Browser test client. No real money, hardware-backed storage or native radios are claimed. */
(()=>{'use strict';
const $=s=>document.querySelector(s),app=$('#app'),enc=new TextEncoder(),dec=new TextDecoder();
const iconPaths={wallet:'M3 7h15v14H3z M3 7V4h13v3 M14 12h7v5h-7z M17 14.5h.1',send:'M5 19 19 5 M5 5h14v14',receive:'M19 5 5 19 M5 5v14h14',plus:'M12 5v14 M5 12h14',offline:'m2 2 20 20 M8.5 16a5 5 0 0 1 6.5-.3 M12 20h.01 M2 8a16 16 0 0 1 4-2 M10 4a17 17 0 0 1 12 4 M5 12a11 11 0 0 1 3-2 M14 9a11 11 0 0 1 5 3',arrow:'M4 12h16 m-6-6 6 6-6 6',back:'M20 12H4 m6-6-6 6 6 6',activity:'M6 3h12v18l-3-2-3 2-3-2-3 2z M9 8h6 M9 12h6',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',sync:'M20 7a8 8 0 0 0-14-1L3 9 M3 4v5h5 M4 17a8 8 0 0 0 14 1l3-3 M21 20v-5h-5',shield:'M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6z m-4 9 3 3 5-6',qr:'M3 3h6v6H3z M15 3h6v6h-6z M3 15h6v6H3z M15 15h2v2h-2z M19 15h2v6h-6v-2',check:'m5 12 4 4L19 6'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${iconPaths[n]||iconPaths.wallet}"/></svg>`;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const b64=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unb64=s=>{if(typeof s!=='string'||!s.length||s.length>24000||! /^[A-Za-z0-9_-]+$/.test(s))throw Error('Invalid code encoding');const bytes=Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));if(b64(bytes)!==s)throw Error('Non-canonical encoding');return bytes;};
const sha=async s=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',typeof s==='string'?enc.encode(s):s))].map(n=>n.toString(16).padStart(2,'0')).join('');
const walletId=async pub=>'pa_'+(await sha(unb64(pub))).slice(0,32);
const canonical=o=>o===null||typeof o!=='object'?JSON.stringify(o):Array.isArray(o)?`[${o.map(canonical).join(',')}]`:`{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${canonical(o[k])}`).join(',')}}`;
function rawToDer(sig){const raw=new Uint8Array(sig);if(raw.length!==64)throw Error('Invalid signature');const integer=b=>{while(b.length>1&&b[0]===0)b=b.slice(1);if(b[0]&128)b=Uint8Array.from([0,...b]);return [2,b.length,...b]};const values=[...integer(raw.slice(0,32)),...integer(raw.slice(32))];return Uint8Array.from([48,values.length,...values]);}
function derToRaw(sig){const s=new Uint8Array(sig);if(s.length<8||s.length>72||s[0]!==48||s[1]!==s.length-2)throw Error('Invalid signature');let i=2;const out=new Uint8Array(64);for(let part=0;part<2;part++){if(s[i++]!==2)throw Error('Invalid signature');let n=s[i++];if(n<1||n>33||i+n>s.length)throw Error('Invalid signature');let b=s.slice(i,i+n);i+=n;if(b.length===33){if(b[0]!==0)throw Error('Invalid signature');b=b.slice(1);}out.set(b,part*32+32-b.length);}if(i!==s.length)throw Error('Invalid signature');return out;}
function peek(raw){if(typeof raw!=='string'||raw.length>23000)throw Error('Invalid payment size');const parts=raw.split('.');if(parts.length!==3||parts[0]!=='p1')throw Error('Not a Paila code');const data=JSON.parse(dec.decode(unb64(parts[1])));if(data.v!==1)throw Error('Unsupported payment version');return data;}
async function sign(kind,data){const encoded=b64(enc.encode(JSON.stringify(data))),sig=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},keyPair.privateKey,enc.encode(`paila:${kind}:v1:${encoded}`));return `p1.${encoded}.${b64(rawToDer(sig))}`;}
async function verify(kind,raw,pub){const data=peek(raw),parts=raw.split('.'),key=await crypto.subtle.importKey('spki',unb64(pub),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);if(!await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,derToRaw(unb64(parts[2])),enc.encode(`paila:${kind}:v1:${parts[1]}`)))throw Error('Signature verification failed');return data;}
const amount=n=>'Rs '+(n/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
function paisa(text,max=10000000){if(!/^\d{1,8}(\.\d{1,2})?$/.test(text.trim()))throw Error('Enter a positive amount with up to two decimals');const [whole,fraction='']=text.trim().split('.');const n=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(n)||n<1||n>max)throw Error('Amount is outside the allowed limit');return n;}
function nameValid(name){if(typeof name!=='string'||!name.trim()||name.length>48||/[\u0000-\u001F\u007F-\u009F\u202A-\u202E\u2066-\u2069]/u.test(name))throw Error('Enter a name (1–48 characters, no control characters)');return name.trim();}
const uuid=()=>crypto.randomUUID();
let db,keyPair,root={queue:[],incoming:[],outgoing:[]},route='Wallet',method='Online',recipient='',payment='',receiveCode='',busy=false,connected=false,message='',error='';
async function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open('paila-test-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('wallet');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});}
const get=key=>new Promise((resolve,reject)=>{const r=db.transaction('wallet').objectStore('wallet').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const put=(key,value)=>new Promise((resolve,reject)=>{const tx=db.transaction('wallet','readwrite');tx.objectStore('wallet').put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});
const save=()=>put('state',root);
async function api(path,envelope){const r=await fetch(path,{method:envelope?'POST':'GET',headers:envelope?{'Content-Type':'application/json'}:{},body:envelope?JSON.stringify({envelope}):undefined,signal:AbortSignal.timeout(15000),redirect:'error'});const data=await r.json();if(!r.ok){const e=Error(data.error?.message||'Server error');e.code=data.error?.code;e.status=r.status;throw e;}return data;}
const call=async(op,data={},opId=uuid())=>api('/v1/actions',await sign('request',{v:1,walletId:root.wallet.walletId,op,opId,ts:Date.now(),data}));
async function config(){const c=await api('/v1/config');if(c.mode!=='test'||c.protocol!==1||await sha(unb64(c.issuerPublicKey))!==c.issuerFingerprint)throw Error('Not a valid Paila test server');if(root.config&&root.config.issuerPublicKey!==c.issuerPublicKey)throw Error('Server identity changed. Payments stopped.');return c;}
async function create(name){root.config=await config();const pub=b64(await crypto.subtle.exportKey('spki',keyPair.publicKey));root.wallet=await api('/v1/wallets',await sign('register',{v:1,publicKey:pub,name:nameValid(name),opId:uuid(),ts:Date.now()}));if(root.wallet.walletId!==await walletId(pub))throw Error('Wallet identity mismatch');await save();connected=true;message='Your wallet has Rs 1,000 test credit.';}
function failedPermanent(e){return [400,403,404,409].includes(e.status)||e.code==='TOPUP_LIMIT';}
async function sync(){await config();for(const job of [...root.queue].filter(j=>j.status==='queued')){try{await call(job.op,job.data,job.id);root.queue=root.queue.filter(j=>j.id!==job.id);message=job.op==='pay'?'Payment settled.':job.op==='reserve'?'Offline note is ready.':job.op==='topup'?'Rs 1,000 test credit added.':'Done.';await save();}catch(e){if(failedPermanent(e)){job.status='failed';job.error=e.message;await save();error=e.message;}else throw e;}}for(const r of root.incoming.filter(r=>r.status==='pending')){try{await call('redeem',{payment:r.packet},r.opId);r.status='settled';await save();}catch(e){if(failedPermanent(e)){r.status='rejected';r.error=e.message;await save();}else throw e;}}root.wallet=await call('state');for(const o of root.outgoing){const n=root.wallet.vouchers.find(n=>n.id===o.id);if(n?.status==='redeemed')o.status=n.recipient===o.to?'settled':'conflict';if(n?.status==='reclaimed')o.status='refunded';}await save();connected=true;}
async function enqueue(op,data={}){if(root.queue.some(j=>j.status==='queued'))throw Error('Resolve the queued request before creating another one');root.queue.push({id:uuid(),op,data,status:'queued'});await save();message='Request saved for the server.';await sync();}
async function receive(){if(!root.wallet)throw Error('Set up online first');const pub=b64(await crypto.subtle.exportKey('spki',keyPair.publicKey));return sign('receive',{v:1,walletId:root.wallet.walletId,publicKey:pub,name:root.wallet.name,requestId:uuid(),createdAt:Date.now(),expiresAt:Date.now()+86400000});}
async function readReceive(raw){const p=peek(raw);const r=await verify('receive',raw,p.publicKey);nameValid(r.name);if(await walletId(r.publicKey)!==r.walletId||!Number.isSafeInteger(r.createdAt)||!Number.isSafeInteger(r.expiresAt)||r.createdAt>Date.now()+300000||r.expiresAt<=Date.now()||r.expiresAt-r.createdAt>86400000||! /^[A-Za-z0-9_-]{16,80}$/.test(r.requestId))throw Error('Invalid or expired receive code');return r;}
async function readPayment(raw){const p=peek(raw);const hop=p.hop===undefined?0:p.hop;if(!Number.isSafeInteger(hop)||hop<0||hop>3)throw Error('Transfer chain is too long or invalid');const links=p.chain===undefined?[]:p.chain;if(!Array.isArray(links)||links.length!==hop)throw Error('Transfer chain does not match hop count');const n=await verify('voucher',hop===0?p.voucher:peek(links[0]).voucher,root.config.issuerPublicKey);if(n.issuer!==root.config.issuerFingerprint||await walletId(n.ownerKey)!==n.owner)throw Error('Invalid issuer or owner');if(!Number.isSafeInteger(n.amount)||n.amount<1||n.amount>500000)throw Error('Invalid offline amount');if(n.expiresAt-n.createdAt!==86400000||Date.now()>=n.expiresAt)throw Error('Offline note expired');const ancestors=[];let ph=null,pa=n.amount,pto=null;for(let i=0;i<hop;i++){if(typeof links[i]!=='string')throw Error('Broken chain link');const ld=peek(links[i]);if((ld.hop===undefined?0:ld.hop)!==i)throw Error('Broken chain continuity');const lf=typeof ld.fromKey==='string'?ld.fromKey:(i===0?n.ownerKey:null);if(!lf)throw Error('Chain link is missing its sender key');if(i===0){if(await walletId(lf)!==n.owner)throw Error('Only the note owner can start a transfer');}else{if(await walletId(lf)!==pto)throw Error('Chain sender does not follow the previous hop');if(ld.prev!==ph)throw Error('Chain link does not reference the previous transfer');}await verify('payment',links[i],lf);if(ld.to===await walletId(lf))throw Error('Choose another wallet');const la=ld.amountMinor;if(!Number.isSafeInteger(la)||la<1||la>pa)throw Error('Chain amount exceeds what was received');const lh=await sha(canonical(ld));ancestors.push({to:ld.to,amount:la,hash:lh});ph=lh;pa=la;pto=await walletId(lf);}
const senderKey=typeof p.fromKey==='string'?p.fromKey:n.ownerKey;if(hop===0){if(await walletId(senderKey)!==n.owner)throw Error('Only the note owner can start a transfer');}else{if(await walletId(senderKey)!==pto)throw Error('Transfer sender does not follow the chain');if(p.prev!==ph)throw Error('Transfer does not reference the previous transfer');}await verify('payment',raw,senderKey);if(p.to!==root.wallet.walletId)throw Error('This payment is for another wallet');const amount=p.amountMinor===undefined?pa:p.amountMinor;if(!Number.isSafeInteger(amount)||amount<1||amount>pa)throw Error('Payment exceeds the available value');if(!Number.isSafeInteger(p.createdAt)||p.createdAt>Date.now()+300000)throw Error('Invalid payment time');return {note:n,hash:await sha(canonical(p)),amount,hop};}
async function offline(raw,value,method){const r=await readReceive(raw);if(r.walletId===root.wallet.walletId)throw Error('Choose another wallet');if(root.queue.some(j=>j.status==='queued'))throw Error('Resolve your queued request first');const myKey=b64(await crypto.subtle.exportKey('spki',keyPair.publicKey));const own=root.wallet.vouchers.filter(n=>n.status==='reserved'&&n.amount>=value&&n.expires>Date.now()&&!root.outgoing.some(o=>o.id===n.id)).sort((a,b)=>a.amount-b.amount)[0];let packet,entry,newHop=0;
if(own){await verify('voucher',own.certificate,root.config.issuerPublicKey);packet=await sign('payment',{v:1,voucher:own.certificate,fromKey:myKey,to:r.walletId,requestId:r.requestId,createdAt:Date.now(),amountMinor:value,hop:0});entry={id:own.id,parent:null,amount:value,to:r.walletId,name:r.name,packet,status:'prepared'};}
else{const cand=[];for(const inc of root.incoming){if(inc.status!=='pending'&&inc.status!=='settled')continue;try{const p=peek(inc.packet);const ph=p.hop===undefined?0:p.hop;const spent=root.outgoing.filter(o=>o.parent===inc.id).reduce((x,o)=>x+o.amount,0);if(inc.amount-spent>=value)cand.push({inc,parentHop:ph,remain:inc.amount-spent});}catch{}}cand.sort((a,b)=>a.remain-b.remain);const best=cand[0];if(!best)throw Error('No reserved balance covers this amount. Top up the offline pocket while online');newHop=best.parentHop+1;const parentData=peek(best.inc.packet);const parentHash=await sha(canonical(parentData));packet=await sign('payment',{v:1,fromKey:myKey,to:r.walletId,requestId:r.requestId,createdAt:Date.now(),amountMinor:value,hop:newHop,prev:parentHash,chain:[...(parentData.chain||[]),best.inc.packet]});entry={id:await sha(canonical(peek(packet))),parent:best.inc.id,amount:value,to:r.walletId,name:r.name,packet,status:'prepared'};}
if(method==='QR'&&newHop>1)throw Error('Chain too long for QR. Use Bluetooth.');root.outgoing.push(entry);await save();payment=packet;message='Payment saved. Share the same code with this recipient; do not create it again.';}
async function accept(raw){const p=await readPayment(raw);const old=root.incoming.find(r=>r.id===p.hash);if(old){message='This payment is already saved.';return;}root.incoming.push({id:p.hash,amount:p.amount,packet:raw,hash:p.hash,status:'pending',opId:uuid()});await save();message='Payment received. Pending server settlement, not spendable yet.';}
async function run(fn){if(busy)return;busy=true;error='';render();try{await fn();}catch(e){error=e.message||'Could not complete action';if(e instanceof TypeError||e.name==='TimeoutError'||e.name==='NetworkError')connected=false;}finally{busy=false;render();}}
function nav(to){route=to;error='';message='';payment='';recipient='';const focusHeading=()=>{$('.screen-content h1')?.focus({preventScroll:true});};if(to==='Receive')run(async()=>{receiveCode=await receive()}).then(focusHeading);else{render();focusHeading();}$('.page')?.scrollTo(0,0);}
function qr(raw){if(!raw)return '';try{const q=new window.PailaQR.Code(-1,window.PailaQR.Level.M);q.addData(raw);q.make();const n=q.getModuleCount(),padding=4;let d='';for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(q.isDark(y,x))d+=`M${x+padding} ${y+padding}h1v1h-1z`;return `<div class="qr-box"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${n+8} ${n+8}" role="img" aria-label="Scannable Paila signed code"><rect width="100%" height="100%" fill="white"/><path d="${d}" fill="black"/></svg></div>`;}catch{return '<p>Code is too large for QR. Copy the signed text below.</p>';}}
const primary=(label,action,disabled=false)=>`<button class="primary" data-action="${action}" ${disabled||busy?'disabled':''}>${label}</button>`;
const queued=()=>root.queue.some(j=>j.status==='queued');
const date=n=>new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Katmandu',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(n));
// Interface layer. The signed protocol, queue and settlement code above remain unchanged.
Object.assign(iconPaths,{copy:'M9 9h12v12H9z M15 9V3H3v12h6',close:'m6 6 12 12 M6 18 18 6',clock:'M12 8v5l3 2 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',info:'M12 11v6 M12 7h.01 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',bluetooth:'m7 7 10 10-5 5V2l5 5L7 17',wifi:'M2 8a16 16 0 0 1 20 0 M5 12a11 11 0 0 1 14 0 M8 16a6 6 0 0 1 8 0 M12 20h.01',nfc:'M5 6H3v14h14v-2 M8 3h13v12H8z M12 7h5v4h-5z',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v2 M12 20v2 M2 12h2 M20 12h2 M5 5l1 1 M18 18l1 1 M5 19l1-1 M18 6l1-1',moon:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11',chevron:'m9 5 7 7-7 7',phone:'M7 2h10a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2 M10 18h4',globe:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0 M2 12h20 M12 2c6 6 6 14 0 20-6-6-6-14 0-20'});
const formValues={};
let lastView='',lastNav=0,theme='auto';
try{theme=localStorage.getItem('paila-appearance')||'auto';}catch{}
if(!['auto','light','dark'].includes(theme))theme='auto';
document.documentElement.dataset.theme=theme;
const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');
const shortId=id=>escape(id.slice(0,9)+'…'+id.slice(-5));
const avatar=name=>`<span class="avatar" aria-hidden="true">${escape([...name.trim()][0]?.toUpperCase()||'P')}</span>`;
const amountMarkup=value=>{const [whole,fraction]=(value/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).split('.');return `<span class="currency">Rs</span><strong class="major">${whole}<span class="fraction">.${fraction}</span></strong>`;};
const heading=(title,description='')=>`<div class="page-heading"><h1 tabindex="-1">${title}</h1>${description?`<p>${description}</p>`:''}</div>`;
const action=(text,name,disabled=false)=>`<button class="primary with-disc" data-action="${name}" ${disabled||busy?'disabled':''}><span>${text}</span><span class="action-disc">${icon('arrow')}</span></button>`;
const submit=(text,disabled=false)=>`<button class="primary with-disc" type="submit" ${disabled||busy?'disabled':''}><span>${text}</span><span class="action-disc">${icon('arrow')}</span></button>`;
const statusNames={reserved:'Ready',prepared:'Ready to share',pending:'Pending',settled:'Settled',redeemed:'Settled',reclaimed:'Refunded',refunded:'Refunded',rejected:'Rejected',conflict:'Conflict',expired:'Expired'};
const chip=status=>`<span class="status-chip ${escape(status)}">${icon(['settled','redeemed'].includes(status)?'check':['pending','prepared'].includes(status)?'clock':'offline')}${escape(statusNames[status]||status)}</span>`;
function entry(e){const name={welcome:'Welcome credit',test_topup:'Credit added',offline_reserve:'Offline note reserved',offline_payment:'Offline payment settled',offline_refund:'Expired note refund'}[e.kind]||e.peerName;return `<div class="transaction"><div class="icon-box ${e.amountMinor>0?'credit':''}">${icon(e.amountMinor>=0?'receive':'send')}</div><div class="row-text"><strong>${escape(name)}</strong><time>${escape(date(e.created))} · NPT</time></div><span class="value ${e.amountMinor>0?'positive':''}">${e.amountMinor>0?'+':'−'}${amount(Math.abs(e.amountMinor)).replace('Rs ','')}</span></div>`;}
function shell(content){const has=!!root.wallet,index=route==='Activity'?1:route==='Settings'?2:0;return `<header class="top"><a href="/" class="wordmark" aria-label="Paila home"><img src="/logo.svg" alt="" width="32" height="32">paila</a><div class="top-actions"><span class="tag">Test wallet</span>${has?`<button class="icon-button" data-nav="Receive" aria-label="Show my receive code">${icon('qr')}</button>`:''}</div></header><main class="page" id="main-content">${has&&!['Wallet','Activity','Settings'].includes(route)?`<button class="back" data-nav="Wallet">${icon('back')}Back to wallet</button>`:''}${error?`<div class="notice error" role="alert">${icon('shield')}<span>${escape(error)}</span><button data-action="dismiss" aria-label="Dismiss error">×</button></div>`:''}${message&&!payment?`<div class="notice" role="status">${icon('check')}<span>${escape(message)}</span><button data-action="dismiss" aria-label="Dismiss message">×</button></div>`:''}${queued()?`<div class="notice warning" role="status">${icon('clock')}<span>Request saved. Waiting for the server—sync again rather than paying twice.</span></div>`:''}${content}${busy?'<p class="progress-status" role="status"><span class="spinner" aria-hidden="true"></span>Working…</p>':''}</main>${has?`<nav class="navigation" aria-label="Main navigation"><span class="nav-pill" aria-hidden="true"></span>${['Wallet','Activity','Settings'].map((r,i)=>`<button class="nav-item ${i===index?'active':''}" data-nav="${r}" ${i===index?'aria-current="page"':''}>${icon(['wallet','activity','settings'][i])}<span>${r}</span></button>`).join('')}</nav>`:''}`;}
function content(){
 if(!root.wallet)return `<div class="screen-content setup-layout"><section class="setup-hero"><img src="/wallet-art.webp" alt=""><h1 class="intro" tabindex="-1">Take it<br>offline.</h1><p>Prepare online.<br>Exchange without a signal.</p></section><form id="setup-form" class="card setup-card"><div class="setup-credit"><div><p class="eyebrow">Your first wallet</p><h2>Start with test money.</h2></div><div class="icon-box">${icon('plus')}</div></div><div class="row between"><span class="credit-value">Rs 5,000</span><span class="tag">Test credit</span></div><label>Your name<input name="name" autocomplete="given-name" required maxlength="48" placeholder="What should we call you?"></label>${submit('Create my test wallet')}<p class="small muted">No bank account. No cash-out.<br>These aren't real rupees.</p></form><p class="setup-note">${icon('shield')}<span>This browser keeps your wallet key. Clearing its site data loses access. Android has a separate native app; phone features aren't simulated here.</span></p></div>`;
 const w=root.wallet;
 if(route==='Wallet'){
 const offlineValue=w.vouchers.filter(n=>n.status==='reserved'&&n.expires>Date.now()&&!root.outgoing.some(o=>o.id===n.id)).reduce((a,n)=>a+n.amount,0);
 return `<div class="screen-content wallet-layout"><div class="greeting"><div><p class="eyebrow">नमस्ते · Namaste,</p><h1 tabindex="-1">${escape(w.name)}</h1></div>${avatar(w.name)}</div><section class="wallet-main"><section class="card balance" aria-label="${connected?'Available test balance':'Saved test balance'}"><img class="balance-art" src="/wallet-art.webp" alt=""><div class="balance-top"><span>${connected?'Available balance':'Saved balance'}</span><span class="tag">Test NPR</span></div><div class="amount" data-testid="balance" aria-label="${amount(w.balanceMinor)} test credit">${amountMarkup(w.balanceMinor)}</div><div class="balance-bottom"><span>Not real money</span><button class="balance-add" data-action="topup" ${busy||queued()||Date.now()<w.nextTopupAt?'disabled':''}>${icon('plus')}Add test</button></div></section><div class="quick-actions"><button class="quick send" data-nav="Send">${icon('send')}Send</button><button class="quick" data-nav="Receive">${icon('receive')}Receive</button></div><section class="card pocket"><div class="row"><div class="icon-box">${icon('offline')}</div><div class="row-text"><h3>Offline pocket</h3><p>${offlineValue?'Reserved for offline exchange.':'Prepare before you lose signal.'}</p></div></div><div class="row between"><strong class="pocket-value">${amount(offlineValue)}</strong><button class="link-button" data-nav="Offline">Manage offline notes ${icon('arrow')}</button></div></section></section><section class="wallet-history"><div class="section-head"><h2>Recent activity</h2><button class="link-button" data-nav="Activity">See all ${icon('arrow')}</button></div><div class="transactions">${w.activity.slice(0,3).map(entry).join('')}</div><div class="connection"><span><i class="dot ${connected?'':'off'}"></i>${connected?'Connected · test server':'Offline · saved balance'}</span><button class="link-button" data-action="sync" ${busy?'disabled':''}>${icon('sync')}Sync</button></div></section></div>`;
 }
 if(route==='Receive')return `<div class="screen-content receive-layout">${heading('Receive money.','Let the sender scan or copy your code.')}<section class="card qr-card">${qr(receiveCode)}<div><h2>${escape(w.name)}</h2><p class="short-id">${shortId(w.walletId)}</p></div><button class="secondary" data-action="copy-receive">${icon('copy')}Copy receive code</button><details class="code-details"><summary>View signed code</summary><label>Receive code<textarea id="receive-code" readonly>${escape(receiveCode)}</textarea></label><p class="wallet-id">${escape(w.walletId)}</p></details></section><form id="receive-form" class="card"><div class="icon-box">${icon('offline')}</div><h3>Someone paid offline?</h3><p class="small muted">Paste their payment below. It's saved now and confirmed when you reconnect.</p><label>Payment code<textarea name="payment" required placeholder="Paste their p1.… payment"></textarea></label>${submit('Save received payment')}<p class="explain">${icon('clock')}Pending receipts aren't spendable yet.</p></form><p class="explain receive-footer">${icon('shield')}Wallet names are self-chosen. Always check the code with the person you're paying.</p></div>`;
 if(route==='Send')return `<div class="screen-content send-layout">${heading(payment?'Ready to share.':'Send money.',payment?'Keep this code until the receiver has it.':'')}<div class="tabs" role="group" aria-label="Payment method"><button class="tab ${method==='Online'?'selected':''}" data-method="Online" ${payment?'disabled':''} aria-pressed="${method==='Online'}">${icon('globe')}Online</button><button class="tab ${method==='QR'?'selected':''}" data-method="QR" ${payment?'disabled':''} aria-pressed="${method==='QR'}">${icon('offline')}Offline QR</button></div><div class="method-footnote"><p>${method==='Online'?'Internet required.':'Final confirmation needs internet.'}</p><button class="link-button" data-action="radios" aria-label="Explain Android nearby methods">${icon('phone')}Nearby</button></div>${payment?`<section class="card qr-card"><div class="receipt-emblem pending">${icon('clock')}</div><h2>Payment saved</h2>${chip('prepared')}<p class="small muted">The note is locked to this recipient. Show or resend this same code if delivery fails.</p>${qr(payment)}<button class="secondary" data-action="copy-payment">${icon('copy')}Copy payment</button><details class="code-details"><summary>View saved payment code</summary><label>Saved payment code<textarea id="payment-code" readonly>${escape(payment)}</textarea></label></details><p class="explain">${icon('clock')}Not a settled receipt. The receiver must reconnect.</p></section>`:`<form id="send-form"><div class="card"><label>Receiver's code<textarea name="recipient" required placeholder="Paste their Paila receive code">${escape(recipient)}</textarea></label><p class="small muted">We'll check the signature before you confirm.</p></div><div class="amount-field"><label for="send-amount">Amount in test rupees</label><div class="amount-line"><span aria-hidden="true">Rs</span><input class="amount-input" id="send-amount" name="amount" inputmode="decimal" placeholder="0.00" required aria-describedby="available-hint"></div><p class="small" id="available-hint">${method==='Online'?amount(w.balanceMinor)+' available':'Send any amount up to your reserved balance.'}</p></div>${method==='Online'?'<label>Note (optional)<input name="note" maxlength="120" placeholder="Tea, lunch, a little thank you…"></label>':`<div class="notice warning">${icon('info')}<span>Keep a reserved offline balance first. The receiver gets pending credit until settlement.</span></div>`}${submit('Review payment',queued())}<p class="explain">${icon('shield')}Test credit only. Nothing moves until you confirm.</p></form>`}</div>`;
 if(route==='Offline')return `<div class="screen-content offline-layout">${heading('Your offline pocket.','Put a little aside before you disconnect.')}<div class="step-row" aria-label="Offline payment steps"><div class="step current"><span>1</span><span>Prepare online</span></div><div class="step"><span>2</span><span>Share offline</span></div><div class="step"><span>3</span><span>Settle online</span></div></div><form id="reserve-form" class="card"><div class="row between"><h3>Prepare a note</h3><span class="tag">Max Rs 5,000</span></div><label>Note value in rupees<input name="amount" inputmode="decimal" value="100" required></label><div class="preset-row" role="group" aria-label="Note amount presets">${[50,100,250].map(n=>`<button type="button" class="preset" data-preset="${n}">Rs ${n}</button>`).join('')}</div>${submit('Reserve this amount',queued())}<p class="small muted">Moves money out of your available balance. Partial spends allowed, valid for 24 hours.</p></form><section><div class="section-head"><h2>Your notes</h2><span class="small muted">${w.vouchers.length} total</span></div><div class="stack">${w.vouchers.length?w.vouchers.map(n=>{const status=n.status==='reserved'?(root.outgoing.some(o=>o.id===n.id)?'prepared':n.expires<=Date.now()?'expired':'reserved'):n.status;return `<section class="note-ticket"><div class="ticket-line"><h3>${amount(n.amount)}</h3>${chip(status)}</div><div class="ticket-bottom"><span>Expires ${date(n.expires)} · NPT</span>${n.status==='reserved'&&Date.now()>=n.expires+604800000?`<button class="link-button" data-refund="${n.id}">Refund expired note</button>`:''}</div></section>`;}).join(''):`<div class="empty-state">${icon('offline')}<h3>No notes yet.</h3><p>Prepare your first amount above. It will be waiting here when you need it.</p></div>`}</div></section><details class="code-details"><summary>When can an unused note be refunded?</summary><p class="small muted">After its 24-hour life and a further seven-day redemption window. This gives an offline receiver time to reconnect before a refund can happen.</p></details></div>`;
 if(route==='Activity')return `<div class="screen-content activity-layout">${heading('Every payment.','Pending and settled. Clearly separated.')}${root.incoming.length||root.outgoing.length?`<section class="stack"><h2>Offline exchanges</h2>${root.incoming.map(r=>`<section class="note-ticket"><div class="ticket-line"><h3>${amount(r.amount)}</h3>${chip(r.status)}</div><div class="row"><div class="icon-box">${icon('receive')}</div><div><strong>Received offline</strong><p class="small muted">${r.status==='pending'?'Waiting for the server. Not spendable yet.':r.status==='settled'?'Included in your available balance.':escape(r.error)}</p></div></div></section>`).join('')}${root.outgoing.map(r=>`<section class="note-ticket"><div class="ticket-line"><h3>${amount(r.amount)}</h3>${chip(r.status)}</div><div><strong>To ${escape(r.name)}</strong><p class="small muted">Offline exchange</p></div>${r.status==='prepared'?`<button class="secondary" data-outbox="${r.id}">Show same payment code</button>`:''}</section>`).join('')}</section>`:''}<section><div class="section-head"><h2>Settled activity</h2><span class="small muted">Test NPR</span></div><div class="transactions">${w.activity.map(entry).join('')}</div></section></div>`;
 return `<div class="screen-content settings-layout">${heading('Make it yours.')}<section class="settings-profile">${avatar(w.name)}<div><h2>${escape(w.name)}</h2><p class="short-id">${shortId(w.walletId)}</p></div></section><section class="card"><div class="row"><div class="icon-box">${icon('sun')}</div><div><h3>Appearance</h3><p class="small muted">Your choice stays on this browser.</p></div></div><div class="theme-switch" role="group" aria-label="Appearance">${[['auto','System'],['light','Light'],['dark','Dark']].map(([id,label])=>`<button data-theme="${id}" aria-pressed="${theme===id}">${label}</button>`).join('')}</div><p class="small muted">Reduced motion follows your device setting.</p></section><section class="card"><div class="setting-row"><div class="row"><div class="icon-box">${icon('globe')}</div><h3>Connection</h3></div><span class="tag"><i class="dot ${connected?'':'off'}"></i>${connected?'Online':'Offline'}</span></div><p class="wallet-id">${escape(location.origin)}</p>${action('Sync now','sync')}<details class="code-details"><summary>Server identity</summary><p class="small muted">Payments stop if this issuer key changes.</p><p class="wallet-id">${escape(root.config.issuerFingerprint)}</p></details></section><section class="card"><div class="row"><div class="icon-box credit">${icon('plus')}</div><h3>Credit</h3></div><p class="small muted">Add Rs 5,000 once every 24 hours. No real deposits or withdrawals.</p>${action('Add Rs 5,000','topup',queued()||Date.now()<w.nextTopupAt)}${Date.now()<w.nextTopupAt?`<p class="small muted">Next top-up: ${date(w.nextTopupAt)} · NPT</p>`:''}</section>${root.queue.filter(j=>j.status==='failed').map(j=>`<div class="notice error"><span>Rejected request: ${escape(j.error)}</span></div>`).join('')}<section class="card"><h3>This device</h3><p class="small muted">Your wallet key lives in this browser profile. Clearing site data loses access; recovery is not available.</p><button class="secondary" data-action="radios">${icon('phone')}About phone-to-phone methods</button><p class="small muted">Browser storage is not Android Keystore. Camera and nearby connections need the native Android app.</p></section><p class="app-footer">Paila 0.2 · Test environment<br>No real NPR or guaranteed offline settlement.</p></div>`;
}
app.addEventListener('input',event=>{const field=event.target;if(field.form&&field.name)(formValues[field.form.id]??={})[field.name]=field.value;});
function focusSelector(el){if(!el||!app.contains(el))return null;if(el.form&&el.name)return `#${CSS.escape(el.form.id)} [name="${CSS.escape(el.name)}"]`;if(el.id)return '#'+CSS.escape(el.id);for(const key of ['action','nav','method','theme','preset'])if(el.dataset?.[key])return `[data-${key}="${CSS.escape(el.dataset[key])}"]`;return null;}
function render(){
 const view=root.wallet?route:'Setup',changed=view!==lastView,previousPage=$('.page'),scroll=previousPage?.scrollTop||0,active=document.activeElement,focus=focusSelector(active),selection=active?.selectionStart,selectionEnd=active?.selectionEnd;
 const oldBalance=$('[data-testid=balance]')?.textContent;
 app.innerHTML=shell(content());
 for(const area of app.querySelectorAll('label textarea')){const label=area.closest('label');area.setAttribute('aria-label',[...label.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent).join(' ').trim());}
 for(const form of app.querySelectorAll('form'))for(const field of form.querySelectorAll('input[name],textarea[name]'))if(formValues[form.id]?.[field.name]!==undefined)field.value=formValues[form.id][field.name];
 const page=$('.page');if(page)page.scrollTop=changed?0:scroll;
 if(!changed&&focus&&!$('#confirm').open){const replacement=app.querySelector(focus);if(replacement&&!replacement.disabled){replacement.focus({preventScroll:true});if(typeof selection==='number'&&replacement.setSelectionRange){try{replacement.setSelectionRange(selection,selectionEnd);}catch{}}}}
 const navIndex=route==='Activity'?1:route==='Settings'?2:0,pill=$('.nav-pill');
 if(pill){const desktop=matchMedia('(min-width:1000px)').matches,position=i=>desktop?`translateY(${i*60}px)`:`translateX(${i*100}%)`;pill.style.transform=position(navIndex);if(lastView&&!motionQuery.matches&&lastNav!==navIndex)pill.animate([{transform:position(lastNav)},{transform:position(navIndex)}],{duration:280,easing:'cubic-bezier(.2,.8,.2,1)'});}
 if(changed&&!motionQuery.matches){$('.screen-content')?.animate([{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'translateY(0)'}],{duration:280,easing:'cubic-bezier(.2,.8,.2,1)'});}
 const balance=$('[data-testid=balance]');
 if(balance){const major=balance.querySelector('.major');let size=parseFloat(getComputedStyle(major).fontSize);while(balance.scrollWidth>balance.clientWidth+1&&size>24){size-=1;major.style.fontSize=size+'px';}if(!changed&&oldBalance&&oldBalance!==balance.textContent&&!motionQuery.matches)balance.animate([{opacity:.45,transform:'translateY(3px)'},{opacity:1,transform:'translateY(0)'}],{duration:220,easing:'ease-out'});}
 lastView=view;lastNav=navIndex;
}
function openSheet(title,inside,onConfirm=null){const d=$('#confirm'),returnFocus=focusSelector(document.activeElement)||'#send-form button[type=submit]';if(d.open)d.close();d.innerHTML=`<form method="dialog"><div class="sheet-handle" aria-hidden="true"></div><div class="sheet-heading"><h2 id="dialog-title">${escape(title)}</h2><button class="icon-button" type="submit" value="cancel" aria-label="Close dialog">${icon('close')}</button></div>${inside}${onConfirm?'<button class="primary with-disc" value="confirm"><span>Confirm</span><span class="action-disc">'+icon('arrow')+'</span></button><button class="cancel-button" value="cancel">Cancel</button>':'<button class="primary" value="cancel">Got it</button>'}</form>`;d.returnValue='';d.onclose=()=>{const target=app.querySelector(returnFocus);if(target&&!target.disabled)target.focus({preventScroll:true});};d.querySelector('form').addEventListener('submit',event=>{event.preventDefault();const confirmed=event.submitter?.value==='confirm';d.close();if(confirmed&&onConfirm)run(onConfirm);},{once:true});d.showModal();}
async function confirmPayment(title,details,callback){openSheet(title,`<p class="sheet-kind">${icon('shield')}Test credit only</p>${details}`,callback);}
function radioSheet(){openSheet('Phone-to-phone methods',`<p class="small muted">These need the native Android app. This browser can't perform Bluetooth, Wi-Fi Direct or NFC exchanges.</p><div class="radio-option"><span class="icon-box">${icon('bluetooth')}</span><div><h3>Bluetooth</h3><p>Pair nearby phones, then exchange the signed payment.</p></div></div><div class="radio-option"><span class="icon-box">${icon('wifi')}</span><div><h3>Wi-Fi Direct</h3><p>Connect two phones directly, without a router.</p></div></div><div class="radio-option"><span class="icon-box">${icon('nfc')}</span><div><h3>NFC</h3><p>A two-tap exchange between compatible Android phones. Not a bank-card terminal payment.</p></div></div><div class="notice warning">${icon('info')}<span>Android source is included. A built APK and real-phone testing are still required.</span></div>`);}
async function copyCode(raw,button){try{await navigator.clipboard.writeText(raw);const old=button.innerHTML;button.innerHTML=icon('check')+'Copied';$('#copy-status').textContent='Signed code copied.';setTimeout(()=>{if(button.isConnected)button.innerHTML=old;},1800);}catch{error='Clipboard unavailable. Open “View signed code” and copy the text.';render();$('details.code-details')?.setAttribute('open','');}}
app.addEventListener('click',e=>{
 const button=e.target.closest('button');if(!button||button.disabled)return;
 if(button.dataset.nav){if(button.dataset.nav==='Send')method='Online';nav(button.dataset.nav);return;}
 if(button.dataset.theme){theme=button.dataset.theme;document.documentElement.dataset.theme=theme;try{localStorage.setItem('paila-appearance',theme);}catch{}render();return;}
 if(button.dataset.method){if(payment)return;method=button.dataset.method;recipient=$('[name=recipient]')?.value||'';render();return;}
 if(button.dataset.preset){const field=$('#reserve-form [name=amount]');field.value=button.dataset.preset;field.dispatchEvent(new Event('input',{bubbles:true}));field.focus({preventScroll:true});return;}
 if(button.dataset.refund){confirmPayment('Refund expired note?',`<p class="small muted">The server checks that the redemption window is closed.</p>`,()=>enqueue('reclaim',{noteId:button.dataset.refund}));return;}
 if(button.dataset.outbox){payment=root.outgoing.find(o=>o.id===button.dataset.outbox).packet;method='QR';route='Send';render();return;}
 switch(button.dataset.action){
 case'dismiss':message='';error='';render();break;
 case'sync':run(sync);break;
 case'topup':confirmPayment('Add credit?',`<p class="review-amount">Rs 5,000.00</p><div class="review-lines"><div class="review-line"><span>To</span><span>${escape(root.wallet.name)}</span></div><div class="review-line"><span>Daily allowance</span><span>Once every 24 hours</span></div></div><p class="small muted">This isn't a bank deposit or real money.</p>`,()=>enqueue('topup'));break;
 case'copy-receive':copyCode(receiveCode,button);break;
 case'copy-payment':copyCode(payment,button);break;
 case'radios':radioSheet();break;
 }
});
app.addEventListener('submit',e=>{
 e.preventDefault();const form=e.target,fd=new FormData(form);
 if(form.id==='setup-form')run(()=>create(String(fd.get('name'))));
 if(form.id==='reserve-form'){try{const n=paisa(String(fd.get('amount')),500000);confirmPayment('Prepare this note?',`<p class="review-amount">${amount(n)}</p><div class="review-lines"><div class="review-line"><span>From</span><span>${connected?'Available balance':'Saved balance'}</span></div><div class="review-line"><span>Valid for</span><span>24 hours</span></div><div class="review-line"><span>Use</span><span>Any amount up to the note</span></div></div><p class="small muted">Set aside now. Share offline later.</p>`,()=>enqueue('reserve',{amountMinor:n}));}catch(e){error=e.message;render();}}
 if(form.id==='receive-form')run(()=>accept(String(fd.get('payment')).trim()));
 if(form.id==='send-form'){const raw=String(fd.get('recipient')).trim(),text=String(fd.get('amount')),note=String(fd.get('note')||'');recipient=raw;
 run(async()=>{const r=await readReceive(raw),n=paisa(text,method==='Online'?10000000:500000);if(r.walletId===root.wallet.walletId)throw Error('Choose another wallet');const chosenMethod=method;
 await confirmPayment('Check your payment',`<p class="review-amount">${amount(n)}</p><div class="review-recipient">${avatar(r.name)}<div><h3>${escape(r.name)}</h3><p class="short-id">${shortId(r.walletId)}</p></div></div><div class="review-lines"><div class="review-line"><span>Method</span><span>${chosenMethod==='Online'?'Online':'Offline · pending'}</span></div><div class="review-line"><span>Fee</span><span>Rs 0.00</span></div>${note&&chosenMethod==='Online'?`<div class="review-line"><span>Note</span><span>${escape(note)}</span></div>`:''}</div><p class="small muted">${chosenMethod==='Online'?'The server must confirm this transfer.':'The receiver cannot spend it until the server confirms settlement.'}</p><details class="code-details"><summary>Check full wallet ID</summary><p class="wallet-id">${escape(r.walletId)}</p><p class="small muted">Names are self-chosen. Compare this with your recipient.</p></details>`,async()=>{if(chosenMethod==='Online'){await enqueue('pay',{to:r.walletId,amountMinor:n,note});if(!root.queue.some(j=>j.status==='failed')){route='Wallet';delete formValues['send-form'];recipient='';}}else await offline(raw,n,chosenMethod);});});}
});
window.addEventListener('online',()=>{if(root.wallet)run(sync)});
window.addEventListener('offline',()=>{connected=false;render()});
motionQuery.addEventListener('change',()=>{if(motionQuery.matches)for(const a of document.getAnimations())a.finish();});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(!$('#confirm').open)render();},100)});
window.PailaTest={snapshot:()=>structuredClone(root),protocol:{rawToDer,derToRaw,peek,verify,readReceive,readPayment,sha,canonical,paisa}};
(async()=>{try{if(!window.isSecureContext||!crypto.subtle)throw Error('Use HTTPS or localhost for the browser test client');db=await openDb();keyPair=await get('keys');if(!keyPair){keyPair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},false,['sign','verify']);await put('keys',keyPair);}root=await get('state')||root;render();if(root.wallet)run(sync);}catch(e){error=e.message;render();}})();
})();
